### ISSUE TITLE
No results from chatGPT/login page appears

### ISSUE THREAD

**Issue by Britman72** [st1vms/gptauto#1]
Testing this out for the first time using the simple example "ask a question". Followed all instructions then opened Firefox and logged into chatgpt.

After entering a question in the terminal, results returned are (None,None). 

It looks like it's timing out because it's redirecting to the openai login page.

Exception has occurred: TimeoutException
Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16
  File "/Users/britman/gptauto/selgym.py", line 47, in wait_element_by
    return WebDriverWait(driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/britman/gptauto/gptauto.py", line 205, in ask_chatgpt
    input_area = wait_element_by(
  File "/Users/britman/gptauto/test.py", line 4, in <module>
    res = gptauto.ask_chatgpt(QUESTION,
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

Am I missing something obvious?

Thanks!

**Comment by st1vms** [comment]
There is a bunch of things that needs to be updated, this library is pretty immature and outdated as you can already tell by the requirement `undected-chromedriver`, also the `selgym` library was embedded instead of using the official one, which got updated over time...

ChatGPT platform have changed a lot from last commit, so there should be a bunch of updates to make...

Sorry for the inconvenience, I will try to post updates as soon as possible : )

**Comment by st1vms** [comment]
@Britman72 You're invited to give a try to latest v0.1.1 version, it is a brand new scraper.
